#!/bin/bash


# apt-get install -y qemu qemu-user-static binfmt-support

if [[ -z $1 ]]; then
    echo "Must provide an image name!"
    exit 1
fi

#{{{ Trap ctrl-c , clean-up and exit
trap ctrl_c INT
function cleanup_all() {

    echo "** END **"

    sudo killall -9 /usr/bin/qemu-arm-static &> /dev/null
    sleep 2

    set +e
    sudo umount $TMP/boot

#    sudo umount $TMP/dev
#    sudo umount $TMP/proc
#    sudo umount $TMP/sys

    sudo umount ${TMP}

    sudo losetup -d $DEV

    rmdir $TMP
    set -e
}

function ctrl_c() {
    set +e
    echo
    echo
    echo "** User interrupt!  cleaning up."
    echo
    
    cleanup_all

    exit 1
}

#}}}

TGT=$1
ARCH='ArchLinuxARM-rpi-3-latest.tar.gz'

if [[ ! -e $ARCH ]]; then
    wget http://os.archlinuxarm.org/os/$ARCH
fi


qemu-img create -f raw $TGT 4G
DEV=$(sudo losetup --find --show $TGT)


sudo parted --script $DEV mklabel msdos
sudo parted --script $DEV mkpart primary fat32 0% 200M
sudo parted --script $DEV mkpart primary ext4 200M 100%


sudo mkfs.vfat -F32 ${DEV}p1
sudo mkfs.ext4 -F ${DEV}p2

TMP=$(mktemp -d)
sudo mount ${DEV}p2 $TMP
sudo mkdir ${TMP}/boot
sudo mount ${DEV}p1 ${TMP}/boot

sudo tar -xpf $ARCH -C $TMP &> /dev/null

#sudo mount -t proc none ${TMP}/proc
#sudo mount -t sysfs none ${TMP}/sys
#sudo mount -o bind /dev ${TMP}/dev


#sudo mv ${TMP}/etc/resolv.conf ${TMP}/etc/resolv.conf.bak
#sudo cp /etc/resolv.conf ${TMP}/etc/resolv.conf
#sudo cp /usr/bin/qemu-arm-static ${TMP}/usr/bin/

sudo cp -a ./_ExtraRootfs/* ${TMP} &> /dev/null

#sudo chroot ${TMP} bash -c /root/_setup_initial
#sudo chroot ${TMP} bash -c /root/_setup_ExtraExec

#sudo mv ${TMP}/etc/resolv.conf ${TMP}/etc/resolv.conf.BKP

##sudo systemd-nspawn -q --capability=all --bind=/sys/fs/cgroup --bind=/etc/resolv.conf -D ${TMP} env http_proxy='http://172.17.0.1:3128' bash -c /root/_setup_initial
sudo systemd-nspawn -q --capability=all --bind=/sys/fs/cgroup --bind=/etc/resolv.conf -D ${TMP} bash -c /root/_setup_initial
#sudo systemd-nspawn -q --capability=all --bind=/sys/fs/cgroup --bind=/etc/resolv.conf -D ${TMP} bash -c /root/_setup_ExtraExec
##sudo systemd-nspawn -q --capability=all --bind=/sys/fs/cgroup --bind=/etc/resolv.conf -D ${TMP} env http_proxy='http://172.17.0.1:3128' bash -c /root/_setup_ExtraExec
sudo systemd-nspawn -q --capability=all --bind=/sys/fs/cgroup --bind=/etc/resolv.conf -D ${TMP} bash -c /root/_setup_ExtraExec

#sudo mv ${TMP}/etc/resolv.conf.BKP ${TMP}/etc/resolv.conf

sudo rm -rf ${TMP}/_ExtraExec
sudo rm -rf ${TMP}/root/_setup*

cleanup_all


