#!/bin/bash

# apt-get install -y qemu qemu-user-static binfmt-support

if [[ -z $1 ]]; then
    echo "Must provide an image name!"
    exit 1
fi

#{{{ Trap ctrl-c , clean-up and exit
trap ctrl_c INT
function cleanup_all() {

    echo "** END create **"
    echo

    sudo killall -9 /usr/bin/qemu-arm-static &> /dev/null
    sleep 2

    set +e
    sudo umount $TMP/boot

    sudo umount ${TMP}

    sudo losetup -d $DEV

    rmdir $TMP
    set -e
}

function ctrl_c() {
    set +e
    echo
    echo
    echo "** User interrupt!  cleaning up."
    echo
    
    cleanup_all

    exit 1
}

#}}}

TGT=$1
ARCH=$2
SIZE=$3

if [[ ! -e $ARCH ]]; then
    wget http://os.archlinuxarm.org/os/$ARCH
fi


qemu-img create -f raw $TGT $3
DEV=$(sudo losetup --find --show $TGT)


sudo parted --script $DEV mklabel msdos
sudo parted --script $DEV mkpart primary fat32 0% 200M
sudo parted --script $DEV mkpart primary ext4 200M 100%


sudo mkfs.vfat -F32 ${DEV}p1
sudo mkfs.btrfs -f ${DEV}p2

TMP=$(mktemp -d)
sudo mount ${DEV}p2 $TMP
sudo mkdir ${TMP}/boot
sudo mount ${DEV}p1 ${TMP}/boot

sudo tar -xpf $ARCH -C $TMP &> /dev/null

cleanup_all


