#!/bin/bash

#{{{ Trap ctrl-c , clean-up and exit
trap ctrl_c INT
function cleanup_all() {

#    sudo umount SD_root/dev
#    sudo umount SD_root/proc
#    sudo umount SD_root/sys

    sudo umount ${TMP}/boot
    sudo umount ${TMP}
    sudo kpartx -d /dev/$DEV
    sudo losetup -d /dev/$DEV

    rmdir $TMP

}

function ctrl_c() {
    set +e
    echo
    echo
    echo "** User interrupt!  cleaning up."
    echo
    
    cleanup_all $1

    exit 1
}

#}}}

if [[ -z $1 ]]; then
    echo "into-image image_name [cmd to run from /mnt/work]"
    exit 0
fi

TGT=$1
CMD=$2

DEV=$(basename $(sudo losetup --find --show $TGT))
sudo kpartx -a /dev/$DEV

TMP=$(mktemp -d)
sudo mount /dev/mapper/${DEV}p2 $TMP
sudo mkdir -p ${TMP}/boot 
sudo mount /dev/mapper/${DEV}p1 ${TMP}/boot


if [[ -z $CMD ]]; then
    sudo systemd-nspawn -q --as-pid2 --bind $PWD:/archpi --bind-ro /etc/resolv.conf  -D ${TMP}/  /bin/bash 
else
    echo "$1: $2"
    sudo systemd-nspawn -q --as-pid2 --bind $PWD:/archpi --bind-ro /etc/resolv.conf  -D ${TMP}/  /bin/bash -c "cd /archpi; export PATH=\$PWD:\$PWD/_recipes:\$PATH ; $CMD"
fi

cleanup_all


