#!/bin/bash

CMD=$(basename $0)

if [[ ! -e /etc/systemd/network/eth0.network ]]; then
    cp -a $PWD/_recipes/_fixedIp-on-eth0/. /. &>/dev/null
fi

sed -i "s!^DHCPServer=no!DHCPServer=yes!" /etc/systemd/network/eth0.network
