#!/bin/bash -e
#
# Setup mini dev environment
#
if [[ 1 == $(_is-done minidev) ]]; then
    exit 0
fi

pacman -Syu --noconfirm sudo vim gcc cmake make dosfstools parted wget btrfs-progs multipath-tools qemu-headless

echo 'alarm ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

echo '/dev/sda1 /mnt/work' >> /etc/fstab


_mark-as-done minidev

